-- MySQL Script generated by MySQL Workbench
-- 08/23/15 17:42:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nuevoPhp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nuevoPhp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nuevoPhp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `nuevoPhp` ;

-- -----------------------------------------------------
-- Table `nuevoPhp`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuevoPhp`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `tipo` ENUM('Admin', 'Invitado') NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuevoPhp`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuevoPhp`.`Proyectos` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `numeroDeFases` INT NOT NULL COMMENT '',
  `Usuarios_idUsuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProyecto`)  COMMENT '',
  INDEX `fk_Proyectos_Usuarios1_idx` (`Usuarios_idUsuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Proyectos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `nuevoPhp`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuevoPhp`.`Fases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuevoPhp`.`Fases` (
  `idFase` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Proyectos_idProyecto` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFase`)  COMMENT '',
  INDEX `fk_Fases_Proyectos1_idx` (`Proyectos_idProyecto` ASC)  COMMENT '',
  CONSTRAINT `fk_Fases_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyecto`)
    REFERENCES `nuevoPhp`.`Proyectos` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nuevoPhp`.`Defectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nuevoPhp`.`Defectos` (
  `idDefecto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codigo` VARCHAR(45) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `Fases_idFase` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDefecto`)  COMMENT '',
  INDEX `fk_Defectos_Fases1_idx` (`Fases_idFase` ASC)  COMMENT '',
  CONSTRAINT `fk_Defectos_Fases1`
    FOREIGN KEY (`Fases_idFase`)
    REFERENCES `nuevoPhp`.`Fases` (`idFase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
